LICENSE, README.md
=> Add README.md and LICENSE

REFERENCE.md, metadata.json
=> release 0.5.0

manifests/interface.pp
=> dont make `$destination_addresses` as optional, remove useless validation

.editorconfig, .github/workflows/ci.yml, .github/workflows/release.yml, .gitignore, .msync.yml, .overcommit.yml, .pmtignore, .rspec, .rspec_parallel, .rubocop.yml, .yardopts, Dockerfile, Gemfile, Rakefile, spec/spec_helper.rb
=> modulesync 4.1.0

CHANGELOG.md, Rakefile, metadata.json
=> release 0.6.0

CHANGELOG.md, Gemfile, metadata.json
related PR: https://github.com/voxpupuli/modulesync_config/pull/737
=> release 0.6.1

CHANGELOG.md, metadata.json
=> Release 0.6.2

README.md, lib/facter/wireguard_pubkeys.rb
=> Add fact to export public keys

REFERENCE.md, manifests/init.pp
=> add option to purge unknown wg keys

CHANGELOG.md, metadata.json
=> Release 0.7.0

CHANGELOG.md, metadata.json
=> Release 0.8.0

.github/CONTRIBUTING.md, .github/workflows/ci.yml, .msync.yml, Gemfile, Rakefile
=> modulesync 4.2.0

.msync.yml, Gemfile, Rakefile, lib/facter/wireguard_pubkeys.rb, spec/classes/wireguard_spec.rb, spec/defines/interface_spec.rb, spec/spec_helper.rb
=> modulesync 5.0.0

manifests/init.pp
Provides possibility to configure interfaces in hiera
=> Provide hiera integration

CHANGELOG.md, REFERENCE.md, metadata.json
=> Release 1.0.0

.github/workflows/ci.yml, .sync.yml, spec/acceptance/init_spec.rb, spec/spec_helper_acceptance.rb
=> Enable basic acceptance tests

manifests/interface.pp, spec/classes/wireguard_spec.rb
This tests the `$wireguard::interfaces` parameter and removes a dependency cycle.
Fixes #52
=> (#52) Fix dependency cycle

CHANGELOG.md, metadata.json
=> Release 2.0.2

CHANGELOG.md, REFERENCE.md, metadata.json
=> Release Version 2.0.3

CHANGELOG.md, metadata.json
=> Release 2.0.4

manifests/interface.pp, manifests/provider/wgquick.pp, spec/defines/interface_spec.rb, templates/wireguard_conf.epp
wg-quick has hooks for pre/post up/down, this module should have an option to configure them
=> Add pre/post up/down commands for wgquick

CHANGELOG.md, REFERENCE.md, metadata.json
=> Release Version 2.1.0

.github/workflows/ci.yml, .msync.yml, Gemfile, Rakefile, spec/spec_helper.rb
=> modulesync 5.4.0

CHANGELOG.md, REFERENCE.md, metadata.json
=> Release 2.2.0

manifests/interface.pp, manifests/provider/wgquick.pp, spec/defines/interface_spec.rb, templates/wireguard_conf.epp
The wg-quick is missing MTU Parameter
=> Add mtu to wg-quick

CHANGELOG.md, metadata.json
=> Release 3.1.2

CHANGELOG.md, metadata.json
=> Release 4.0.1

REFERENCE.md, manifests/init.pp, manifests/interface.pp, manifests/provider/systemd.pp, manifests/provider/wgquick.pp, spec/defines/interface_spec.rb, spec/fixtures/test_files/peers2.netdev, templates/netdev.epp, templates/wireguard_conf.epp
This enables people to overwrite the default in hiera.
=> Make default AllowedIPs= configureable

spec/defines/interface_spec.rb
This PR proves that we have a bug. It's fixed in #101
=> Add unit tests for firewalling without dst ips

metadata.json
=> puppetlabs/systemd: Allow 6.x
