voxpupuli/puppet-wireguard

- REFERENCE.md
- manifests/interface.pp
> puppet:wireguard: set default for `$source_addresses` to `[]`

- REFERENCE.md
- manifests/interface.pp
> wireguard:interface: default `input_interface` to `networking.primary` fact

- REFERENCE.md
- manifests/interface.pp
The endpoint parameter is only required if wireguard should connect to a
remote site. That's not always possible. For example in situations where
the remote site is behind a NAT gateway and/or has a dynamic IP address.
For such setups you can create a 'passive' configuration that listens
for incoming packets.
> Make endpoint parameter optional

- REFERENCE.md
- manifests/interface.pp
> Implement PersistentKeepalive parameter

- manifests/interface.pp
- spec/defines/interface_spec.rb
Previously `$destination_addresses` was an array with the public
ipv6/ipv4 addresses. Those were used as destination address in the
firewall rules. People might have dynamic local ips so this won't
work/creates a lot of noise due to constant firewall rule updates. As a
fix, it was already possible to set `$destination_addresses` to an empty
Array (`[]`). But passing this to the `daddr` parameter in ferm::rule
created a broken firewall rule. This patch sets the `daddr` parameter to
`undef` if `$destination_addresses` is an empty array.
> Make filtering on dest addr optional

- REFERENCE.md
- manifests/interface.pp
- spec/defines/interface_spec.rb
> Implement description attribute for network interface

- REFERENCE.md
- manifests/interface.pp
- spec/defines/interface_spec.rb
> Implement `mtu` param to configure MTUBytes

- lib/facter/wireguard_pubkeys.rb
Previously we assumed that the path to a key always contains an exact
amount of slashes and the filename only a single dot. Although the path
is still hardcoded, we now select the filename from the path and trim
the last `.pub`. People can now use multiple dots in their key names.
> fact: support keyfiles with multiple dots

- REFERENCE.md
- manifests/interface.pp
- spec/defines/interface_spec.rb
- spec/fixtures/test_files/peers.netdev
- spec/fixtures/test_files/peers.network
- templates/netdev.epp
- templates/network.epp
- types/peers.pp
The current version of this module only supports one peer per
wireguard interface.
But the systemd-networkd wireguard implementation allows multiple
WireguardPeer sections.
This PR implement this function with backward compatbility
> Add possibility to add multiple peers

- manifests/interface.pp
- spec/defines/interface_spec.rb
- spec/fixtures/test_files/peers_routes.network
- templates/network.epp
Add route configuration possibility to this module
> Add possibility to define routes

- spec/defines/interface_spec.rb
- spec/fixtures/test_files/peers.netdev
- templates/netdev.epp
- types/peers.pp
this adds a description option to peers, if there a more than one peer
its hard to recognize the peer by reading the config. there a a lot
peers only identfied by a public key and a address, so maybe for
someone its helpful to write the hostname or some other description as
comment over the peer block
> Add description to peers

- manifests/interface.pp
- spec/defines/interface_spec.rb
This PR add a feature to define a private key by parameter. It's optional to prevent old behavior as default.
If the private key is updated, it will generate a new public key file
> Create private_key from parameter if wanted

- manifests/interface.pp
- spec/defines/interface_spec.rb
- templates/netdev.epp
New PR to incorporate changes for PR #47. Attribution of the original author is done by using `Co-authored-by` 😊
WireGuard offers the option to use pre-shared keys per interface. While this option is not required to use WireGuard, if the other party uses pre-shared keys, the connecting client is forced to use this pre-shared key as well.
Fixes #46
> Allow usage of pre-shared keys on interfaces

- manifests/interface.pp
- spec/defines/interface_spec.rb
- spec/fixtures/test_files/peers.netdev
- templates/netdev.epp
- types/peers.pp
`PresharedKey` is a per-peer configuration and should be handled as such. This enables one to set a different preshared key per peer.
> Move preshared_key from interface to peer configuration

- manifests/interface.pp
If you build a wireguard network, based on puppetdb queries. it's possible that there no peers, because they didn't sent there facts at this point.
now the puppet agent will cancel, cause there are no peers.
so my tought is, a warning instead of fail should be enough
> Throw warning instead of fail if peers is empty 

- REFERENCE.md
- manifests/interface.pp
in case `$facts['networking']['ip6']` is empty it returns undef. we need
to filter this out because the ferm module has a strict type and doesn't
allow it.
> Workaround for missing ipv6 addresses

- manifests/interface.pp
- manifests/provider/systemd.pp
- manifests/provider/wgquick.pp
- spec/defines/interface_spec.rb
- templates/wireguard_conf.epp
we are using the $address parameter for the address block in wireguard
config.
this blocks also allows thinks like DNS and dns don't need to be a
CIDR.
This commit will change this and accept a address or a CIDR address
> Fix $addresses hash needs to accept any type of v4 or v6 address

- spec/defines/interface_spec.rb
- templates/wireguard_conf.epp
> Fix wgquick template and extend tests

- README.md
- manifests/interface.pp
This documents that wg-quick and that systemd-network is optional
I link to the Debian manpages because it's the first thing that came up in a web search, but I'm happy to link elsewhere if there's a better reference.
It also adds an extra example using facts, cross-ref from README. I'm not actually sure that *works*, but it feels like something like that is missing from the examples...
> add examples, document systemd-networkd and wg-quick

- REFERENCE.md
- manifests/interface.pp
- manifests/provider/systemd.pp
- manifests/provider/wgquick.pp
After talking to @bastelfreak there is no reason for the 1280-9000 range
> Change mtu to Integer[1200,9000]

- manifests/interface.pp
- spec/defines/interface_spec.rb
This worked in the past but at some point the inheritance to the epp template broke and persistent_keepalive was always set to 0.
> persistent_keepalive: Fix regression - paass persistent_keepalive to systemd config

- .fixtures.yml
- README.md
- REFERENCE.md
- manifests/interface.pp
- spec/defines/interface_spec.rb
> Switch from voxpupuli/ferm to voxpupuli/nftables for firewalling

- manifests/interface.pp
- spec/defines/interface_spec.rb
We create firewall rules for incoming and outgoing packets. We are very strict and filter also for the dst IPs for incoming packets and the src IP for outgoing  packets. In case there are no local IP, because the client might have dynamic IPs, we don't create rules at all. That is a bug. I verified it in https://github.com/voxpupuli/puppet-wireguard/pull/102. This PR fixes it.
> nftables: Handle missing destination addresses

- spec/defines/interface_spec.rb
Usually we parse the src port for incoming packets / the dst port for outgoing packets from the $endpoint param The param is optional, in case you want to create a passive endpoint for clients with dynamic ip addresses In those cases we still need to create firewall rules, but without src port for incoming packets / the dst port To make this all a bit easier, we also added a new parameter, $endpoint_port, which takes precedence over parsing $endpoint.
Previously the catalog compilation failed with:
```
Evaluation Error: Left match operand must result in a String value. Got an Undef Value.
```
Because of: `if $endpoint =~  /:(\d+)$/ {`
This test verifies that the current code is broken.
> Ensure catalog compiles when endpoint is missing

- REFERENCE.md
- manifests/interface.pp
- spec/defines/interface_spec.rb
Usually we parse the src port for incoming packets / the dst port for outgoing packets from the $endpoint param The param is optional, in case you want to create a passive endpoint for clients with dynamic ip addresses In those cases we still need to create firewall rules, but without src port for incoming packets / the dst port To make this all a bit easier, we also added a new parameter, $endpoint_port, which takes precedence over parsing $endpoint.
Previously the catalog compilation failed with:
```
Evaluation Error: Left match operand must result in a String value. Got an Undef Value.
```
Because of: `if $endpoint =~  /:(\d+)$/ {`
https://github.com/voxpupuli/puppet-wireguard/pull/103 verifies that the current code is broken.
Thew new code adds a safeguard to check if $endpoint is …
> Make src port for firwalling configureable]

- REFERENCE.md
- manifests/interface.pp
- manifests/provider/systemd.pp
- manifests/provider/wgquick.pp
- templates/netdev.epp
- templates/wireguard_conf.epp
> Adds "table" parameter to a wireguard interface stanza to be able to set it in the wg-quick/netdev configuration.
> 
> NOTE: I've tested this personally only for wg-quick.
> This Pull Request (PR) fixes the following issues
> 
> Fixes https://github.com/voxpupuli/puppet-wireguard/issues/83
> 
This is a follow up on  
https://github.com/voxpupuli/puppet-wireguard/pull/84
> Adds "table" parameter to a wireguard interface stanza to be able to set it in the wg-quick/netdev configuration.

- REFERENCE.md
- manifests/interface.pp
- manifests/provider/systemd.pp
- spec/defines/interface_spec.rb
- spec/fixtures/test_files/peers_routes.network
- templates/network.epp
Make it possible to define custom sections and settings via hash for systemd network interfaces
None, feature-request
> Add custom sections to systemd network
